version: '3'
services:
  manager:
    container_name: manager
    ports:
      - 9001:9001
    image: registry.cn-hangzhou.aliyuncs.com/hdp-eco/hdp-eco-base
    hostname: manager

  hadoop:
    container_name: hadoop
    image: registry.cn-hangzhou.aliyuncs.com/hdp-eco/hadoop
    hostname: hadoop
    depends_on:
      - manager
  
  hive:
    container_name: hive
    links: 
      - mysql:mysql
    image: registry.cn-hangzhou.aliyuncs.com/hdp-eco/hive
    depends_on:
      - mysql
      - hadoop
      - manager
    hostname: hive
    volumes:
      - ./hive/conf/hive-site.xml:/usr/lib/hive/conf/hive-site.xml
  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    ports:
      - "8888:8888"
    volumes:
      - ./hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - mysql
      - hadoop
      - hive

  mysql:
    container_name: mysql
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./hue/init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: hue
      MYSQL_USER: hue
      MYSQL_PASSWORD: 111111
    ports:
      - 3306:3306
    hostname: mysql