version: '3'
services:
  manager:
    container_name: manager
    ports:
      - 9001:9001
    image: registry.cn-hangzhou.aliyuncs.com/hdp-eco/hdp-eco-base
    hostname: manager
    entrypoint: supervisord -c /etc/supervisord-manager.conf

  hadoop:
    container_name: hadoop
    image: registry.cn-hangzhou.aliyuncs.com/hdp-eco/hadoop
    hostname: hadoop
    depends_on:
      - manager
  
  hive:
    container_name: hive
    links: 
      - mysql:mysql
    image: registry.cn-hangzhou.aliyuncs.com/hdp-eco/hive
    depends_on:
      - mysql
      - hadoop
      - manager
    hostname: hive

  mysql:
    container_name: mysql
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    ports:
      - 3306:3306
    hostname: mysql