# This is the main CeSI toml configuration file. It contains CeSI web application and
# supervisord information to connect

# This is the CeSI's own configuration.
[cesi]
# Database Uri
database = "sqlite:///users.db"                         # Relative path
# Etc
#database = "sqlite:////opt/cesi/< version >/users.db"  # Absolute path
#database = "postgres://<user>:<password>@localhost:5432/<database_name>"
#database = "mysql+pymysql://<user>:<password>@localhost:3306/<database_name>"
activity_log = "/var/log/cesi/activity.log"   # File path for CeSI logs
admin_username = "admin"        # Username of admin user
admin_password = "admin"        # Password of admin user

# This is the definition section for new supervisord node.
[[nodes]]
name = "manager"
environment = ""
username = "admin"
password = "admin"
host = "127.0.0.1"
port = "9001"

[[nodes]]
name = "hadoop"
environment = ""
username = "admin"
password = "admin"
host = "hadoop"
port = "9001"

[[nodes]]
name = "hive"
environment = ""
username = "admin"
password = "admin"
host = "hive"
port = "9001"